apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app.kubernetes.io/name: django_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: django_app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django_app
    spec:
      containers:
      - name: django-app
        image: hell:latest
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-app-secret-v
                key: SECRET_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-app-secret-v
                key: DATABASE_URL
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: django-app-secret-v
                key: DEBUG
          - name: ALLOWED_HOST
            valueFrom:
              secretKeyRef:
                name: django-app-secret-v
                key: ALLOWED_HOSTS
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  ttlSecondsAfterFinished: 50 # Удаляет job через 50сек. после завершения
  backoffLimit: 3 # Кол-во попыток которые делает job для запуска Pod
  template:
    spec:
      containers:

      - name: django-app
        image: hell:latest
        imagePullPolicy: IfNotPresent
        command: ["./manage.py", "migrate", "--no-input"]
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-app-secret-v
                key: SECRET_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-app-secret-v
                key: DATABASE_URL
      restartPolicy: Never
