apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels:
    app.kubernetes.io/name: django_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: django_app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: django_app
    spec:
      containers:
      - name: django-app
        image: hell:latest
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-app-secret
                key: SECRET_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-app-secret
                key: DATABASE_URL
          - name: DEBUG
            valueFrom:
              secretKeyRef:
                name: django-app-secret
                key: DEBUG
          - name: ALLOWED_HOST
            valueFrom:
              secretKeyRef:
                name: django-app-secret
                key: ALLOWED_HOSTS
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: django-app-service
  labels:
    app.kubernetes.io/name: django-app-service
spec:
  selector:
    app.kubernetes.io/name: django_app
  ports:
    - name: app-listener
      protocol: TCP
      port: 80
  type: NodePort