apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 1 */1 *"  # Создает Job каждый месяц первого числа
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 30 # Удаляет job через 30сек. после завершения
      template:
        spec:
          containers:

          - name: django-app
            image: hell:latest
            imagePullPolicy: IfNotPresent
            command: ["./manage.py", "clearsessions"]
            env:
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: django-app-secret-v
                    key: SECRET_KEY
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: django-app-secret-v
                    key: DATABASE_URL
          restartPolicy: Never


