apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 0 1 */1 *"  # Создает Job каждый месяц первого числа
  startingDeadlineSeconds: 40 # На сколько можно просрочить запуск job
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 50 # Удаляет job через 50сек. после завершения
      backoffLimit: 3 # Кол-во попыток которые делает job для запуска Pod
      template:
        spec:
          containers:

          - name: django-app
            image: hell:latest
            imagePullPolicy: IfNotPresent
            command: ["./manage.py", "clearsessions"]
            env:
              - name: SECRET_KEY
                valueFrom:
                  secretKeyRef:
                    name: django-app-secret-v
                    key: SECRET_KEY
              - name: DATABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: django-app-secret-v
                    key: DATABASE_URL
          restartPolicy: Never # Обязательно ставин Never, чтобы контейнер не перезапускался вечно


