apiVersion: batch/v1
kind: Job
metadata:
  name: django-clearsessions
spec:
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: django-app
        image: hell:latest
        imagePullPolicy: IfNotPresent
        command: ["./manage.py", "clearsessions"]
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: django-app-secret-v
                key: SECRET_KEY
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: django-app-secret-v
                key: DATABASE_URL
      restartPolicy: Never

